Repository MORSECorp/snappiershot, pull requests merged in 2020-11, with the labels that each got.

#56 Repository maintenance
  .github/CONTRIBUTOR_CODE_OF_CONDUCT.md
  .github/CONTRIBUTOR_LICENSE_AGREEMENT.md
  .github/workflows/release.yml
  CHANGELOG.md
  CODE_OF_CONDUCT.md
  CONTRIBUTING.md
  poetry.lock
  pyproject.toml
  snappiershot/serializers/constants.py
Labels: Infrastructure, enhancement

#63 Decimal class serializer
  snappiershot/serializers/constants.py
  snappiershot/serializers/json.py
  tests/test_serializers/test_json.py
Labels: enhancement

#62 AssertionError Reporting
  poetry.lock
  pyproject.toml
  snappiershot/plugins/pytest.py
  snappiershot/plugins/tracker.py
  snappiershot/serializers/constants.py
  snappiershot/snapshot.py
  tests/test_plugins/test_tracker.py
  tests/test_serializers/test_utils.py
  tests/test_snapshot.py
Labels: enhancement

#65 v0.2.0
  .github/workflows/release.yml
  poetry.lock
  pyproject.toml
  snappiershot/plugins/pytest.py
  snappiershot/plugins/tracker.py
  snappiershot/serializers/constants.py
  snappiershot/serializers/json.py
  snappiershot/snapshot.py
  tests/test_plugins/test_tracker.py
  tests/test_serializers/test_json.py
  tests/test_serializers/test_utils.py
  tests/test_snapshot.py
Labels: release
