Repository MORSECorp/snappiershot, pull requests merged in 2021-02, with the labels that each got.

#66 Primary Merge Action
  .github/workflows/primary.yml
  .github/workflows/tests.yml
Labels: Infrastructure

#76 [BUG] Metadata Serialization
  snappiershot/snapshot/_file.py
  tests/test_snapshot/test_file.py
Labels: bug

#72 Handle Recursive Objects
  snappiershot/serializers/utils.py
  snappiershot/snapshot/snapshot.py
  tests/test_serializers/test_utils.py
Labels: bug, enhancement

#77 Release of v1.0.0
  .github/workflows/primary.yml
  .github/workflows/tests.yml
  CHANGELOG.md
  CONTRIBUTING.md
  README.md
  poetry.lock
  pyproject.toml
  snappiershot/plugins/tracker.py
  snappiershot/serializers/constants.py
  snappiershot/serializers/io.py
  snappiershot/serializers/json.py
  snappiershot/serializers/optional_module_utils.py
  snappiershot/serializers/utils.py
  snappiershot/snapshot.py
  snappiershot/snapshot/__init__.py
  snappiershot/snapshot/_file.py
  snappiershot/snapshot/_raises.py
  snappiershot/snapshot/metadata.py
  snappiershot/snapshot/snapshot.py
  snappiershot/snapshot/status.py
  tests/test_plugins/test_tracker.py
  tests/test_serializers/test_io.py
  tests/test_serializers/test_json.py
  tests/test_serializers/test_optional_module_utils.py
  tests/test_serializers/test_utils.py
  tests/test_snapshot/__init__.py
  tests/test_snapshot/conftest.py
  tests/test_snapshot/test_file.py
  tests/test_snapshot/test_metadata.py
  tests/test_snapshot/test_raises.py
  tests/test_snapshot/test_snapshot.py
Labels: release

#73 pathlib.Path type encodings
  snappiershot/serializers/constants.py
  snappiershot/serializers/json.py
  tests/test_serializers/test_json.py
Labels: enhancement
